IF OBJECT_ID(N'dbo.DatosAbiertos_Licitaciones_Stage', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.DatosAbiertos_Licitaciones_Stage
    (
        [Codigo] float NULL,
        [Link] nvarchar(255) NULL,
        [CodigoExterno] nvarchar(255) NULL,
        [Nombre] nvarchar(255) NULL,
        [Descripcion] nvarchar(max) NULL,
        [CriteriosRequisitosAmbientales] nvarchar(255) NULL,
        [DescripcionCriteriosRequisitosAmbientales] nvarchar(max) NULL,
        [CriteriosRequisitosSociales] nvarchar(255) NULL,
        [DescripcionCriteriosRequisitosSociales] nvarchar(max) NULL,
        [DescripcionCriteriosRequisitosSociales.1] nvarchar(max) NULL,
        [CriteriosEvaluacion] nvarchar(max) NULL,
        [Tipo de Adquisicion] nvarchar(255) NULL,
        [CodigoEstado] float NULL,
        [Estado] nvarchar(255) NULL,
        [CodigoOrganismo] float NULL,
        [NombreOrganismo] nvarchar(255) NULL,
        [sector] nvarchar(255) NULL,
        [RutUnidad] nvarchar(255) NULL,
        [CodigoUnidad] float NULL,
        [NombreUnidad] nvarchar(255) NULL,
        [DireccionUnidad] nvarchar(255) NULL,
        [ComunaUnidad] nvarchar(255) NULL,
        [RegionUnidad] nvarchar(255) NULL,
        [Informada] float NULL,
        [CodigoTipo] float NULL,
        [Tipo] nvarchar(255) NULL,
        [TipoConvocatoria] float NULL,
        [CodigoMoneda] nvarchar(255) NULL,
        [Moneda Adquisicion] nvarchar(255) NULL,
        [Etapas] float NULL,
        [EstadoEtapas] float NULL,
        [TomaRazon] float NULL,
        [EstadoPublicidadOfertas] float NULL,
        [JustificacionPublicidad] nvarchar(600) NULL,
        [EstadoCS] float NULL,
        [Contrato] float NULL,
        [Obras] float NULL,
        [CantidadReclamos] float NULL,
        [FechaCreacion] datetime NULL,
        [FechaCierre] datetime NULL,
        [FechaInicio] datetime NULL,
        [FechaFinal] datetime NULL,
        [FechaPubRespuestas] datetime NULL,
        [FechaActoAperturaTecnica] datetime NULL,
        [FechaActoAperturaEconomica] datetime NULL,
        [FechaPublicacion] datetime NULL,
        [FechaAdjudicacion] datetime NULL,
        [FechaEstimadaAdjudicacion] datetime NULL,
        [FechaSoporteFisico] datetime NULL,
        [FechaTiempoEvaluacion] float NULL,
        [UnidadTiempoEvaluacion] nvarchar(255) NULL,
        [FechaEstimadaFirma] datetime NULL,
        [FechasUsuario] float NULL,
        [FechaVisitaTerreno] datetime NULL,
        [DireccionVisita] datetime NULL,
        [FechaEntregaAntecedentes] datetime NULL,
        [DireccionEntrega] datetime NULL,
        [Estimacion] nvarchar(500) NULL,
        [FuenteFinanciamiento] nvarchar(255) NULL,
        [VisibilidadMonto] float NULL,
        [MontoEstimado] float NULL,
        [Tiempo] nvarchar(255) NULL,
        [UnidadTiempo] nvarchar(255) NULL,
        [Modalidad] nvarchar(255) NULL,
        [TipoPago] float NULL,
        [ProhibicionContratacion] nvarchar(400) NULL,
        [SubContratacion] float NULL,
        [UnidadTiempoDuracionContrato] float NULL,
        [TiempoDuracionContrato] float NULL,
        [TipoDuracionContrato] nvarchar(255) NULL,
        [JustificacionMontoEstimado] nvarchar(500) NULL,
        [ObservacionContrato] nvarchar(500) NULL,
        [ExtensionPlazo] float NULL,
        [EsBaseTipo] float NULL,
        [UnidadTiempoContratoLicitacion] float NULL,
        [ValorTiempoRenovacion] float NULL,
        [PeriodoTiempoRenovacion] nvarchar(255) NULL,
        [EsRenovable] float NULL,
        [TipoAprobacion] nvarchar(255) NULL,
        [NumeroAprobacion] nvarchar(255) NULL,
        [FechaAprobacion] nvarchar(255) NULL,
        [NumeroOferentes] float NULL,
        [Correlativo] float NULL,
        [CodigoEstadoLicitacion] float NULL,
        [Codigoitem] float NULL,
        [CodigoProductoONU] float NULL,
        [Rubro1] nvarchar(255) NULL,
        [Rubro2] nvarchar(255) NULL,
        [Rubro3] nvarchar(255) NULL,
        [Nombre producto genrico] nvarchar(255) NULL,
        [Nombre linea Adquisicion] nvarchar(255) NULL,
        [Descripcion linea Adquisicion] nvarchar(500) NULL,
        [UnidadMedida] nvarchar(255) NULL,
        [Cantidad] float NULL,
        [CodigoProveedor] float NULL,
        [CodigoSucursalProveedor] float NULL,
        [RutProveedor] nvarchar(255) NULL,
        [NombreProveedor] nvarchar(255) NULL,
        [RazonSocialProveedor] nvarchar(255) NULL,
        [DescripcionProveedor] nvarchar(max) NULL,
        [Monto Estimado Adjudicado] nvarchar(400) NULL,
        [Nombre de la Oferta] nvarchar(255) NULL,
        [Estado Oferta] nvarchar(255) NULL,
        [Cantidad Ofertada] float NULL,
        [Moneda de la Oferta] nvarchar(255) NULL,
        [MontoUnitarioOferta] float NULL,
        [Valor Total Ofertado] float NULL,
        [CantidadAdjudicada] float NULL,
        [MontoLineaAdjudica] float NULL,
        [FechaEnvioOferta] datetime NULL,
        [Oferta seleccionada] nvarchar(255) NULL,
        [Archivo] nvarchar(250) NULL,
        [InstitucionIdOrPortal] nvarchar(5) NULL,
        [MonedaOrigen_Total_Adjudicado] float NULL,
        [ProveedorRut_Numero] int NULL,
        [CLP_Total_Adjudicado] bigint NULL,
        [RutProveedor2] nvarchar(255) NULL
    );
END
GO

IF OBJECT_ID(N'dbo.DatosAbiertos_OC_Stage', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.DatosAbiertos_OC_Stage
    (
        [ID] int NULL,
        [Codigo] nvarchar(255) NULL,
        [Link] nvarchar(255) NULL,
        [Nombre] nvarchar(255) NULL,
        [Descripcion/Obervaciones] nvarchar(max) NULL,
        [Tipo] nvarchar(255) NULL,
        [ProcedenciaOC] nvarchar(255) NULL,
        [EsTratoDirecto] nvarchar(255) NULL,
        [EsCompraAgil] nvarchar(255) NULL,
        [CodigoTipo] float NULL,
        [CodigoAbreviadoTipoOC] nvarchar(255) NULL,
        [DescripcionTipoOC] nvarchar(255) NULL,
        [idPlanDeCompra] nvarchar(255) NULL,
        [codigoEstado] float NULL,
        [Estado] nvarchar(255) NULL,
        [codigoEstadoProveedor] float NULL,
        [EstadoProveedor] nvarchar(255) NULL,
        [FechaCreacion] datetime NULL,
        [FechaEnvio] datetime NULL,
        [FechaSolicitudCancelacion] datetime NULL,
        [fechaUltimaModificacion] datetime NULL,
        [FechaAceptacion] datetime NULL,
        [FechaCancelacion] datetime NULL,
        [tieneItems] float NULL,
        [PromedioCalificacion] float NULL,
        [CantidadEvaluacion] float NULL,
        [MontoTotalOC] float NULL,
        [TipoMonedaOC] nvarchar(255) NULL,
        [MontoTotalOC_PesosChilenos] float NULL,
        [Impuestos] float NULL,
        [TipoImpuesto] nvarchar(255) NULL,
        [Descuentos] float NULL,
        [Cargos] float NULL,
        [TotalNetoOC] float NULL,
        [CodigoUnidadCompra] float NULL,
        [RutUnidadCompra] nvarchar(255) NULL,
        [UnidadCompra] nvarchar(255) NULL,
        [CodigoOrganismoPublico] float NULL,
        [OrganismoPublico] nvarchar(255) NULL,
        [ActividadComprador] nvarchar(500) NULL,
        [CiudadUnidadCompra] nvarchar(255) NULL,
        [RegionUnidadCompra] nvarchar(255) NULL,
        [PaisUnidadCompra] nvarchar(255) NULL,
        [CodigoSucursal] float NULL,
        [RutSucursal] nvarchar(255) NULL,
        [Sucursal] nvarchar(255) NULL,
        [CodigoProveedor] float NULL,
        [NombreProveedor] nvarchar(255) NULL,
        [ActividadProveedor] nvarchar(500) NULL,
        [ComunaProveedor] nvarchar(500) NULL,
        [RegionProveedor] nvarchar(255) NULL,
        [PaisProveedor] nvarchar(255) NULL,
        [Financiamiento] nvarchar(255) NULL,
        [PorcentajeIva] float NULL,
        [Pais] nvarchar(255) NULL,
        [TipoDespacho] float NULL,
        [FormaPago] float NULL,
        [CodigoLicitacion] nvarchar(255) NULL,
        [IDItem] float NULL,
        [codigoCategoria] float NULL,
        [Categoria] nvarchar(500) NULL,
        [codigoProductoONU] float NULL,
        [NombreroductoGenerico] nvarchar(255) NULL,
        [RubroN1] nvarchar(255) NULL,
        [RubroN2] nvarchar(255) NULL,
        [RubroN3] nvarchar(255) NULL,
        [EspecificacionComprador] nvarchar(max) NULL,
        [EspecificacionProveedor] nvarchar(max) NULL,
        [cantidad] float NULL,
        [UnidadMedida] nvarchar(255) NULL,
        [monedaItem] nvarchar(255) NULL,
        [precioNeto] float NULL,
        [totalCargos] float NULL,
        [totalDescuentos] float NULL,
        [totalImpuestos] float NULL,
        [totalLineaNeto] float NULL,
        [Forma de Pago] nvarchar(255) NULL,
        [Archivo] nvarchar(250) NULL,
        [ProveedorRut_Numero] int NULL,
        [ProveedorRut_DV] nvarchar(10) NULL,
        [InstitucionRut_Numero] int NULL,
        [InstitucionRut_DV] nvarchar(10) NULL,
        [IdOrPortal] nvarchar(5) NULL,
        [Total_CLP] bigint NULL,
        [Codigo_ConvenioMarco] nvarchar(255) NULL,
        [sector] nvarchar(255) NULL,
        [RutSucursal2] nvarchar(255) NULL
    );
END
GO
